### ISSUE TITLE
broken link in CustomOperations.java

### ISSUE THREAD

**Issue by barrybecker4** [ensozos/Matrix-Profile#1]
The javadoc says

 * Following is the link to the cheatsheat I've implemented
 * https://www.dataquest.io/blog/images/cheat-sheets/numpy-cheat-sheet.pdf

However, I get a 404 error when I try to access that URL.

**Comment by ensozos** [comment]
Thanks for catching that. There is a plan to refactor this class and add documentation
For now more information about CustomOperation can be found on dll4j-examples repository [NumpyCheatSheat](https://github.com/deeplearning4j/dl4j-examples/blob/master/nd4jexamples/src/main/java/org/nd4j/examples/numpy_cheatsheat/NumpyCheatSheat.java)

**Comment by barrybecker4** [comment]
I get a 404 error when I try to access 
https://github.com/deeplearning4j/dl4j-examples/blob/master/nd4jexamples/src/main/java/org/nd4j/examples/numpy_cheatsheat/NumpyCheatSheat.java

**Comment by ensozos** [comment]
[NumpyCheatSheat fixed url](https://github.com/deeplearning4j/dl4j-examples/tree/master/nd4j-examples/src/main/java/org/nd4j/examples/numpy_cheatsheat)

**Comment by barrybecker4** [comment]
A fix has been merged.
