### ISSUE TITLE
Consider using the gradle wrapper

### ISSUE THREAD

**Issue by barrybecker4** [ensozos/Matrix-Profile#6]
If the gradle wrapper is supplied with the project, them developers of this project will not need to first install gradle.
See https://medium.com/@bherbst/understanding-the-gradle-wrapper-a62f35662ab7

@ensozos, if you agree, I will make a PR to add the gradle wrapper.

**Comment by ensozos** [comment]
I agree that's a good idea

**Comment by barrybecker4** [comment]
This has been added.
